packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@biomejs/biome": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - "@biomejs/biome"
  - better-sqlite3
  - esbuild
  - sharp
  - workerd
