-- farm-in-pocket seed: initial plants master
-- Issue: kako-jun/farm-in-pocket#13
--
-- 一般的な家庭菜園作物 + 観葉植物 20 件。
-- 連作管理に効くため family は正確に Wikipedia ベースで設定する。
-- tags / start_methods は JSON 文字列。thumbnail_url は NULL（Phase 3 で投入）。
-- INSERT OR IGNORE で再適用安全（id は AUTOINCREMENT なので name でユニーク判定にはならない点に注意。
-- 同一 name の重複は plants の運用ルール上発生させない前提）。

INSERT OR IGNORE INTO plants (name, name_en, family, genus, category, tags, start_methods, description, thumbnail_url) VALUES
  ('トマト', 'Tomato', 'ナス科', 'Solanum', 'vegetable',
    '["夏野菜","果菜","定番"]', '["seed","seedling"]',
    '南米原産のナス科。連作障害が出やすいので同じ場所で2〜3年は避ける。', NULL),
  ('ミニトマト', 'Cherry Tomato', 'ナス科', 'Solanum', 'vegetable',
    '["夏野菜","果菜","初心者向け"]', '["seed","seedling"]',
    'トマトより育てやすい家庭菜園定番。プランターでも豊作になりやすい。', NULL),
  ('きゅうり', 'Cucumber', 'ウリ科', 'Cucumis', 'vegetable',
    '["夏野菜","果菜","つる性"]', '["seed","seedling"]',
    'ウリ科。支柱・ネット必須。連作障害が強く出る。', NULL),
  ('なす', 'Eggplant', 'ナス科', 'Solanum', 'vegetable',
    '["夏野菜","果菜"]', '["seed","seedling"]',
    'ナス科。水と肥料を多く欲しがる。連作障害に注意。', NULL),
  ('ピーマン', 'Bell Pepper', 'ナス科', 'Capsicum', 'vegetable',
    '["夏野菜","果菜"]', '["seed","seedling"]',
    'ナス科。比較的丈夫だが連作障害は出る。', NULL),
  ('じゃがいも', 'Potato', 'ナス科', 'Solanum', 'vegetable',
    '["根菜","春植え","秋植え"]', '["bulb"]',
    'ナス科。種芋から育てる。連作障害が強い（そうか病等）。', NULL),
  ('さつまいも', 'Sweet Potato', 'ヒルガオ科', 'Ipomoea', 'vegetable',
    '["根菜","夏","痩せ地OK"]', '["seedling"]',
    'ヒルガオ科。痩せた土でもよく育つ。挿し苗で植える。', NULL),
  ('バジル', 'Basil', 'シソ科', 'Ocimum', 'herb',
    '["ハーブ","夏","料理"]', '["seed","seedling"]',
    'シソ科。トマトのコンパニオンプランツとして優秀。', NULL),
  ('しそ', 'Shiso', 'シソ科', 'Perilla', 'herb',
    '["ハーブ","薬味","和食"]', '["seed","seedling"]',
    'シソ科。こぼれ種で毎年生えるくらい強い。', NULL),
  ('パセリ', 'Parsley', 'セリ科', 'Petroselinum', 'herb',
    '["ハーブ","二年草"]', '["seed","seedling"]',
    'セリ科。発芽までやや時間がかかる。', NULL),
  ('ねぎ', 'Welsh Onion', 'ヒガンバナ科', 'Allium', 'vegetable',
    '["薬味","通年"]', '["seed","seedling"]',
    'ヒガンバナ科ネギ属。再生栽培もできる。', NULL),
  ('レタス', 'Lettuce', 'キク科', 'Lactuca', 'vegetable',
    '["葉菜","春","秋"]', '["seed","seedling"]',
    'キク科。涼しい時期向き。とう立ちに注意。', NULL),
  ('ほうれん草', 'Spinach', 'ヒユ科', 'Spinacia', 'vegetable',
    '["葉菜","秋","冬"]', '["seed"]',
    'ヒユ科。酸性土壌に弱いので苦土石灰で調整。', NULL),
  ('大根', 'Daikon Radish', 'アブラナ科', 'Raphanus', 'vegetable',
    '["根菜","秋"]', '["seed"]',
    'アブラナ科。直まき推奨（移植に弱い）。', NULL),
  ('にんじん', 'Carrot', 'セリ科', 'Daucus', 'vegetable',
    '["根菜","春","秋"]', '["seed"]',
    'セリ科。発芽までの乾燥に弱い。直まき。', NULL),
  ('ひまわり', 'Sunflower', 'キク科', 'Helianthus', 'flower',
    '["花","夏","一年草"]', '["seed"]',
    'キク科。日当たりさえあれば誰でも咲かせられる。', NULL),
  ('チューリップ', 'Tulip', 'ユリ科', 'Tulipa', 'bulb',
    '["球根","春","花壇"]', '["bulb"]',
    'ユリ科。秋植えで春咲き。球根は冷涼な期間が必要。', NULL),
  ('モンステラ', 'Monstera', 'サトイモ科', 'Monstera', 'houseplant',
    '["観葉","室内","耐陰"]', '["seedling"]',
    'サトイモ科。耐陰性が高く室内栽培の定番。', NULL),
  ('ポトス', 'Pothos', 'サトイモ科', 'Epipremnum', 'houseplant',
    '["観葉","室内","つる性"]', '["seedling"]',
    'サトイモ科。水挿しでも増やせる。耐陰性◎', NULL),
  ('サボテン', 'Cactus', 'サボテン科', 'Cactaceae', 'succulent',
    '["多肉","室内","乾燥OK"]', '["seedling"]',
    'サボテン科。水やりは控えめ。日光は好む。', NULL);
